### ISSUE TITLE
dll injector

### ISSUE THREAD

**Issue by Ronaldmcdonaldeats** [fadillzzz/korepi-tools#10]
can you tell me a dll injector please

**Comment by djdoolky76** [comment]
unfortunately, there's no official injector for korepi tools, so you have to use other alternative injectors in the meantime

**Comment by djdoolky76** [comment]
If you want a hassle-free experience, you can use my compiled binary from Minty source, which is intended for lol.dll.

Make sure to rename your korepi launcher to colorpickerV.exe and put lol.dll and my compiled launcher in one directory

https://files.djdoolky76.net/Uploads/korepi-tools/Launcher.rar

**Comment by fadillzzz** [comment]
Follow the advice above or download the injector I've just added and put it in the same folder as Korepi along with the DLL.
