### ISSUE TITLE
Genshin Impact suspended in action 

### ISSUE THREAD

**Issue by MizuHixxx** [fadillzzz/korepi-tools#11]
After adding the md5c.pub path file, korepi closes and through the task manager it shows genshin impact suspended in action. The game does not start even after 10 minutes

**Comment by djdoolky76** [comment]
you need to paste the file directory quickly, or else the game will die 🤣

**Comment by MizuHixxx** [comment]
> you need to paste the file directory quickly, or else the game will die 🤣

ahh with the new launcher it worked fine 
thnx
