### ISSUE TITLE
Infinite [Searching for base address...]

### ISSUE THREAD

**Issue by GamingFun300** [fadillzzz/korepi-tools#13]
![image](https://github.com/fadillzzz/korepi-tools/assets/90178621/bbb4db55-31ef-4889-8635-5de9f7397b7b)
It happens either way - injecting through the injector on this Git, through a third-party injector, or through the Launcher

**Comment by fadillzzz** [comment]
The DLL you're using isn't compatible with the Korepi you're using. Redownload the latest version of each.

**Comment by GamingFun300** [comment]
> The DLL you're using isn't compatible with the Korepi you're using. Redownload the latest version of each.

Well that helped, thanks, but now 0xc0000409 is showing up

**Comment by GamingFun300** [comment]
Version 1.3.1.2 with these files - https://github.com/fadillzzz/korepi-tools/issues/8#issuecomment-2118874322 and the old usage method works without problems

**Comment by fadillzzz** [comment]
> > The DLL you're using isn't compatible with the Korepi you're using. Redownload the latest version of each.
> 
> Well that helped, thanks, but now 0xc0000409 is showing up

If it consistently gives that error code, you might've made a mistake while following the instructions. Keep in mind, that at the moment, the latest version of Korepi is unstable and might crash even when everything is normal.
