### ISSUE TITLE
游戏启动地址设置为cn服客户端会卡在Waiting for GenshinImpact.exe to start...

### ISSUE THREAD

**Issue by godsapple** [fadillzzz/korepi-tools#14]
游戏启动地址设置为cn服客户端会卡在Waiting for GenshinImpact.exe to start...
而global服就不会出现这个问题，能够正常启动游戏注入
![image](https://github.com/fadillzzz/korepi-tools/assets/31956924/77ae435b-26f8-4344-a8c5-a932d6b485fb)
![image](https://github.com/fadillzzz/korepi-tools/assets/31956924/fb955497-f8e6-4e04-812c-3d10c4854063)

**Comment by fadillzzz** [comment]
Closing this as it's no longer relevant with the recent versions
