### ISSUE TITLE
Game closing about 2-3 minutes after it starts, log suggests it fails to confirm subscription info from a URL.

### ISSUE THREAD

**Issue by BreadtheRipper** [fadillzzz/korepi-tools#17]
![image](https://github.com/fadillzzz/korepi-tools/assets/37238148/80df224c-d4e9-4a01-8d13-535b2d884a14)

**Comment by fadillzzz** [comment]
Thanks for reporting the issue. Can you try redownloading the file? https://github.com/fadillzzz/korepi-tools/releases/tag/0.2.0

**Comment by BreadtheRipper** [comment]
Apologies for the late response on this. I redownloaded and can confirm it now works as intended
Thank you!
