### ISSUE TITLE
update whem

### ISSUE THREAD

**Issue by movanoix** [fadillzzz/korepi-tools#20]
can you update pls

**Comment by KhoaDayy** [comment]
U can use this file , it worked at version 4.8 https://drive.google.com/file/d/14MMjACUYZdIhTeJmD7L9F2pCMzuWgfoC/view?usp=drive_link
![Capture](https://github.com/user-attachments/assets/b9132c4e-4d64-40cc-8188-363851eca3b6)

**Comment by KhoaDayy** [comment]
Unzip and rename this file to korepi and drop it into the 0.2.2 folder

**Comment by igorbraga2030** [comment]
> Unzip and rename this file to korepi and drop it into the 0.2.2 folder

Not Working, Be careful guys, I believe it's a virus

**Comment by KhoaDayy** [comment]
This file I got from the Discord server Kitten Bods is working perfectly.

**Comment by KhoaDayy** [comment]
If u dont trust me, i can try it for u [Video](https://streamable.com/jhz0te)

**Comment by zayronnn** [comment]
> If u dont trust me, i can try it for u [Video](https://streamable.com/jhz0te)

Working, sorry brother <3

**Comment by intezya** [comment]
> U can you this file , it worked at version

soo.. it's real working xd

**Comment by chikof** [comment]
> U can you this file , it worked at version 4.8 https://drive.google.com/file/d/14MMjACUYZdIhTeJmD7L9F2pCMzuWgfoC/view?usp=drive_link ![Capture](https://private-user-images.githubusercontent.com/72400535/352072391-b9132c4e-4d64-40cc-8188-363851eca3b6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTY5MzcsIm5iZiI6MTcyMTkxNjYzNywicGF0aCI6Ii83MjQwMDUzNS8zNTIwNzIzOTEtYjkxMzJjNGUtNGQ2NC00MGNjLTgxODgtMzYzODUxZWNhM2I2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE0MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYTczYmU4ZWI2MGI1ZDkzYjNmOTg5MGM3ZjMzZjk3YWUxNmJiMTJjZWMzZjI3MmQ0NzEzMmRmNDE4OWMxYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y70tH2I6NcGIeXZJgT0z1Nis5x4xuR8LB7lNey52JjU)

You leaked your UID in this video btw

**Comment by chikof** [comment]
> If u dont trust me, i can try it for u [Video](https://streamable.com/jhz0te)

You leaked your UID in this video btw

**Comment by KhoaDayy** [comment]
> > If u dont trust me, i can try it for u [Video](https://streamable.com/jhz0te)
> 
> You leaked your UID in this video btw

Oh, I didn't notice. Thank you for reminding me, bro.

**Comment by thienha1** [comment]
well this is not crack, just it from beta release for tester

**Comment by Shaw75** [comment]
> well this is not crack, just it from beta release for tester

no,If you don’t use korepi-tools, it will force you to update

**Comment by Deuteriunt** [comment]
@KhoaDayy 
![image](https://github.com/user-attachments/assets/7bcf8f38-0274-4bf2-821f-5d2f5d168404)
After opening, this pops up

**Comment by KhoaDayy** [comment]
> @KhoaDayy ![image](https://private-user-images.githubusercontent.com/113855835/352180429-7bcf8f38-0274-4bf2-821f-5d2f5d168404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjEwODEsIm5iZiI6MTcyMTkyMDc4MSwicGF0aCI6Ii8xMTM4NTU4MzUvMzUyMTgwNDI5LTdiY2Y4ZjM4LTAyNzQtNGJmMi04MjFmLTVkMmY1ZDE2ODQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQxNTE5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzQ3NjQ5YmNjMDE1NDMwZmFmNjRhM2MwYWZiMTg0YTg5NjcwNzQ1MGI1ZTc1NTVmNDc4Y2M3Yjc0YWM2NDRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OzNj_YXqPCo0eux7C_PWBnbgyMNsYdZ8GVQAJd7J1N4) After opening, this pops up

You must use it with Korepi-tools. Unzip and rename this file to korepi and place it into the 0.2.2 folder like this:
![image](https://github.com/user-attachments/assets/ca8caaaa-fbbe-4431-b775-de1ecae58fe2)

**Comment by Shaw75** [comment]
> After opening, this pops up
still need to use korepi-tools cracked

**Comment by ninhmaxdz** [comment]
thanks so much , u saved many people +1 respect

**Comment by zayronnn** [comment]
@KhoaDayy How do I contact you?

**Comment by KhoaDayy** [comment]
> @KhoaDayy How do I contact 
U can dm via discord: @kynx_06

**Comment by KhoaDayy** [comment]
> @KhoaDayy How do I contact you?

U can dm via discord: @kynx_06

**Comment by Yasodzc9** [comment]
anyone got banned from that tester version yet ?

**Comment by fadillzzz** [comment]
New release which should work with the latest version (1.3.3.0 as of writing). Largely untested. Open a new issue if it doesn't work for you.
https://github.com/fadillzzz/korepi-tools/releases/tag/0.3.0-untested

**Comment by Shaw75** [comment]
Do you still have a beta version of 5.0?

**Comment by Smithzin** [comment]
> Descompacte e renomeie este arquivo para korepi e solte-o na pasta 0.2.2

Como posso entrar em contato com você?
pode atualizar para o 5.0?
