### ISSUE TITLE
update

### ISSUE THREAD

**Issue by KhanhNguyen9872** [fadillzzz/korepi-tools#23]
korepi updated to 5.0

**Comment by jeffersondecastro0** [comment]
Yea pls do

**Comment by noximilien95** [comment]
Add source file for version 5.0, because it is not public. to hack you need a link to 5.0

**Comment by noximilien95** [comment]
To hack the required link to the source file, they are only available to users who have purchased the cheat. if you want a hack, post a link to 5.0

**Comment by KhanhNguyen9872** [comment]
> To hack the required link to the source file, they are only available to users who have purchased the cheat. if you want a hack, post a link to 5.0

not source file, this repo bypass server of korepi to get fake license
and tool public for all users, who purchased it can get result of web server, they can using it to bypass korepi, but i didn't have it
tool: https://github.com/Cotton-Buds/calculator/releases/tag/gi

**Comment by KhanhNguyen9872** [comment]
> > To hack the required link to the source file, they are only available to users who have purchased the cheat. if you want a hack, post a link to 5.0
> 
> not source file, this repo bypass server of korepi to get fake license, tool is public

here is link: https://github.com/Cotton-Buds/calculator/releases/tag/gi

**Comment by ghost** [comment]
> > To hack the required link to the source file, they are only available to users who have purchased the cheat. if you want a hack, post a link to 5.0
> 
> not source file, this repo bypass server of korepi to get fake license and tool public for all users, who purchased it can get result of web server, they can using it to bypass korepi, but i didn't have it tool: https://github.com/Cotton-Buds/calculator/releases/tag/gi

Mods say that they keep on changing the verification type each update

**Comment by pokemc32ryan** [comment]
> > > To hack the required link to the source file, they are only available to users who have purchased the cheat. if you want a hack, post a link to 5.0要破解指向源檔所需的連結，它們僅適用於已購買作弊的使用者。如果你想要一個hack，請發佈一個指向5.0的連結
> > 
> > 
> > not source file, this repo bypass server of korepi to get fake license and tool public for all users, who purchased it can get result of web server, they can using it to bypass korepi, but i didn't have it tool: https://github.com/Cotton-Buds/calculator/releases/tag/gi不是源檔，這個 repo 繞過 korepi 的伺服器來為所有使用者公開假許可證和工具，購買它可以獲得 Web 伺服器的結果，他們可以使用它來繞過 korepi，但我沒有它工具：https://github.com/Cotton-Buds/calculator/releases/tag/gi
> 
> Mods say that they keep on changing the verification type each update版主說他們每次更新都會不斷更改驗證類型

Where? not in announcements

**Comment by Not192** [comment]
Download KP from their github, and get free key from verification from their discord. Althou, 5.0 is cracked, but i suggest y'all to wait till tomorrow if fad posts it or not

**Comment by fadillzzz** [comment]
New release is available https://github.com/fadillzzz/korepi-tools/releases/tag/0.4.0
Closing this issue. Open a new one if there's a problem with the latest release.
