### ISSUE TITLE
Game force close or crash after 5-12 mins...

### ISSUE THREAD

**Issue by thienha1** [fadillzzz/korepi-tools#25]
Not same as before, this korepi added something that can check in-game and shut down when detect something wrong... I just guess this!!

**Comment by fadillzzz** [comment]
Will look into this.

**Comment by casg1** [comment]
same issue here

**Comment by ghost** [comment]
It's korepi issue

**Comment by thienha1** [comment]
> It's korepi issue

It's korepi bot crash not game crash!!

**Comment by fadillzzz** [comment]
Should be fixed with the latest release https://github.com/fadillzzz/korepi-tools/releases/tag/0.4.1

**Comment by casg1** [comment]
yeah it looks like its fixed, thank you so much
