### ISSUE TITLE
it doesnt open

### ISSUE THREAD

**Issue by ukaruu** [fadillzzz/korepi-tools#28]
I followed all the steps idk why it doesnt work rn

**Comment by ghost** [comment]
> I followed all the steps idk why it doesnt work rn

Make sure to complete the korepi steps, change the file name to korepi and run the injector as an administrator.

**Comment by fadillzzz** [comment]
Please give more information. Which Korepi & Korepi-tools versions are you using

**Comment by DJ192** [comment]
> Please give more information. Which Korepi & Korepi-tools versions are you using

The latest versions of Korepi & Tools are v1.4.0.2_fix3.zip & 0.4.5.zip

There would be a file name envsetting in korepi. Run that as admin first. Then rename the v1.4.0.2_fix3 file as korepi. Then run the tools injector as admin.

**Comment by ghost** [comment]
> I followed all the steps idk why it doesnt work rn

There would be a file name envsetting in korepi. Run that as admin first. Then rename the v1.4.0.2_fix3 file as korepi. Then run the tools injector as admin.

**Comment by ukaruu** [comment]
im using both the latest but i cant seem to run it idk why? 


![Screenshot (40)](https://github.com/user-attachments/assets/3fc1d1f4-ccd3-4565-9a0c-78677ce84680)

**Comment by fadillzzz** [comment]
Post the version number. Don't say "latest"

**Comment by ukaruu** [comment]
[0.4.5.zip](https://github.com/user-attachments/files/17001615/0.4.5.zip)

**Comment by ukaruu** [comment]
> [0.4.5.zip](https://github.com/user-attachments/files/17001615/0.4.5.zip)

here it is sorry

**Comment by ukaruu** [comment]
> > [0.4.5.zip](https://github.com/user-attachments/files/17001615/0.4.5.zip)
> 
> here it is sorry

i used  the version v1.4.0.2_fix3 for korepi
