### ISSUE TITLE
[Error] [RSAUtil.cpp:298] 客户端请求数据失败,网络问题或者是服务器问题,如果别人能使用就是你的网络存在问题

### ISSUE THREAD

**Issue by xianyu23333** [fadillzzz/korepi-tools#4]
如题，出现这个问题应该怎么解决

**Comment by fadillzzz** [comment]
Most likely, you didn't install the SSL certificate correctly. It has to be installed into the Trusted Root Certificate Authorities folder.

![image](https://github.com/fadillzzz/korepi-tools/assets/927915/dabf1854-3e1c-4e8a-ae10-8147d79a58cd)

**Comment by xianyu23333** [comment]
ths,i got it
