### ISSUE TITLE
new problem，[OK]> [DLL injection] Process crashed, exit code: 0xc0000409

### ISSUE THREAD

**Issue by xianyu23333** [fadillzzz/korepi-tools#5]
![image](https://github.com/fadillzzz/korepi-tools/assets/50168997/87dc1138-3c6d-4917-8384-416237733391)

**Comment by fadillzzz** [comment]
This is an issue with Korepi itself. You'll want to ask them for help. Make sure you're also using the latest version of Korepi (v1.3.0.1.fix_1 at the time of writing)

**Comment by xianyu23333** [comment]
> This is an issue with Korepi itself. You'll want to ask them for help. Make sure you're also using the latest version of Korepi (v1.3.0.1.fix_1 at the time of writing)

it turned out that there is something wrong with my private server , because the free version do not work too. What else, the v1.3.0.1.fix_1.exe appears the same problem.
