### ISSUE TITLE
[DLL injection] Process crashed, exit code: 0xc0000409

### ISSUE THREAD

**Issue by GamingFun300** [fadillzzz/korepi-tools#8]
![image](https://github.com/fadillzzz/korepi-tools/assets/90178621/1a1a431a-79ec-40ea-a93a-042cbc7d78ab)

**Comment by djdoolky76** [comment]
use 1.3.1.2 instead that version use ssl pinning and may not working on this script anymore

**Comment by ilylust** [comment]
@djdoolky76 do you have v1.3.1.2 laying around by chance?

**Comment by FaizBastomi** [comment]
> use 1.3.1.2 instead that version use ssl pinning and may now working on this script anymore

@djdoolky76 is version 1.3.1.1 works?

**Comment by djdoolky76** [comment]
> > use 1.3.1.2 instead that version use ssl pinning and may now working on this script anymore
> 
> @djdoolky76 is version 1.3.1.1 works?

that works as well but it has camera issue, the above version that I'd mention is good

**Comment by djdoolky76** [comment]
> @djdoolky76 do you have v1.3.1.2 laying around by chance?

yes, here's my mirror link

https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar

**Comment by GamingFun300** [comment]
> use 1.3.1.2 instead that version use ssl pinning and may not working on this script anymore

![image](https://github.com/fadillzzz/korepi-tools/assets/90178621/3440de9a-ab82-412c-82c4-cda7c8f40c63)

**Comment by ilylust** [comment]
> > @djdoolky76 do you have v1.3.1.2 laying around by chance?
> 
> yes, here's my mirror link
> 
> https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar

Still process crashed but different code
![image](https://github.com/fadillzzz/korepi-tools/assets/58314919/78fce433-036c-42ce-8357-1db2f69fb43b)

**Comment by ilylust** [comment]
> > use 1.3.1.2 instead that version use ssl pinning and may not working on this script anymore
> 
> ![image](https://private-user-images.githubusercontent.com/90178621/331814740-3440de9a-ab82-412c-82c4-cda7c8f40c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDk2NzUsIm5iZiI6MTcxNjA0OTM3NSwicGF0aCI6Ii85MDE3ODYyMS8zMzE4MTQ3NDAtMzQ0MGRlOWEtYWI4Mi00MTJjLTgyYzQtY2RhN2M4ZjQwYzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE2MjI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MjA3NDA2M2JkMDU4NTYyMzFhN2JhZmVhMjY4OTI0MGE0ZTBjMmQ5MDQ3ZjI1MGYwZjY5ZDQwMTM3OWVjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0VtdrqqeDf2mPBf4TaV3pgN6trcplNQz-hSXGZL1yA)

Use server.js from sigh branch and change latest_version to 1.3.1.2
https://github.com/fadillzzz/korepi-tools/blob/sigh/server.js

**Comment by djdoolky76** [comment]
> > > @djdoolky76 do you have v1.3.1.2 laying around by chance?
> > 
> > 
> > yes, here's my mirror link
> > https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar
> 
> Still process crashed but different code ![image](https://private-user-images.githubusercontent.com/58314919/331815178-78fce433-036c-42ce-8357-1db2f69fb43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDk2NzQsIm5iZiI6MTcxNjA0OTM3NCwicGF0aCI6Ii81ODMxNDkxOS8zMzE4MTUxNzgtNzhmY2U0MzMtMDM2Yy00MmNlLTgzNTctMWRiMmY2OWZiNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE2MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMmZjMzRhMDE1YzJjMGZlZDVjMWNlYTg0YjQ4YTI1MTRjYTFhODk2NTRjNzJlODY3NTdhMDE3M2E1ZTUxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wsii4eMgyVtvY35gqCEC8j4UwbQ1LzPVqygoosuBs4Y)

You can use my forked version, remember to generate a new cert in ssl_gen and delete the old one installed in your system

https://files.djdoolky76.net/Uploads/korepi-tools/korepi-tools-forked.rar

**Comment by ilylust** [comment]
> > > > @djdoolky76 do you have v1.3.1.2 laying around by chance?
> > > 
> > > 
> > > yes, here's my mirror link
> > > https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar
> > 
> > 
> > Still process crashed but different code ![image](https://private-user-images.githubusercontent.com/58314919/331815178-78fce433-036c-42ce-8357-1db2f69fb43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDk2NzQsIm5iZiI6MTcxNjA0OTM3NCwicGF0aCI6Ii81ODMxNDkxOS8zMzE4MTUxNzgtNzhmY2U0MzMtMDM2Yy00MmNlLTgzNTctMWRiMmY2OWZiNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE2MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMmZjMzRhMDE1YzJjMGZlZDVjMWNlYTg0YjQ4YTI1MTRjYTFhODk2NTRjNzJlODY3NTdhMDE3M2E1ZTUxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wsii4eMgyVtvY35gqCEC8j4UwbQ1LzPVqygoosuBs4Y)
> 
> You can use my forked version, remember to generate a new cert in ssl_gen and delete the old one installed in your system
> 
> https://files.djdoolky76.net/Uploads/korepi-tools/korepi-tools-forked.rar

Works like a charm TY <3

**Comment by FaizBastomi** [comment]
> yes, here's my mirror link
> 
> https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar

@djdoolky76 oh, thanks

**Comment by GamingFun300** [comment]
> > > > @djdoolky76 do you have v1.3.1.2 laying around by chance?
> > > 
> > > 
> > > yes, here's my mirror link
> > > https://files.djdoolky76.net/Uploads/Korepi/4.6/Korepi%20V%201.3.1.2.rar
> > 
> > 
> > Still process crashed but different code ![image](https://private-user-images.githubusercontent.com/58314919/331815178-78fce433-036c-42ce-8357-1db2f69fb43b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNDk2NzQsIm5iZiI6MTcxNjA0OTM3NCwicGF0aCI6Ii81ODMxNDkxOS8zMzE4MTUxNzgtNzhmY2U0MzMtMDM2Yy00MmNlLTgzNTctMWRiMmY2OWZiNDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE2MjI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMmZjMzRhMDE1YzJjMGZlZDVjMWNlYTg0YjQ4YTI1MTRjYTFhODk2NTRjNzJlODY3NTdhMDE3M2E1ZTUxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wsii4eMgyVtvY35gqCEC8j4UwbQ1LzPVqygoosuBs4Y)
> 
> You can use my forked version, remember to generate a new cert in ssl_gen and delete the old one installed in your system
> 
> https://files.djdoolky76.net/Uploads/korepi-tools/korepi-tools-forked.rar

It worked, tysm!
